import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// tutorial
const sidebars: SidebarsConfig = {
  //tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  tutorialSidebar: [
    // doc: 単純
    "hello", // documentId
    // doc: ラベル付き
    {
      type: "doc",
      id: "intro", // documentId
      label: "イントロダクション", // sidebarLabel
    },
    // html: サイドバーにhtmlを追加
    {
      type: "html",
      value: "<hr />",
    },

    {
      type: "category",
      label: "基本的な使い方",
      collapsible: true, // ▼ を表示
      collapsed: false, // 開く
      link: {
        type: "generated-index",
        title: "基本的な使い方",
        description: "ドキュサウルスの基本編です。",
        slug: "/tutorial-basics/",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "tutorial-basics",
        },
      ],
    },
    {
      type: "category",
      label: "上級編",
      collapsible: true, // ▼ を表示
      collapsed: true, // 閉じる
      link: {
        type: "generated-index",
        title: "上級編",
        description: "ドキュサウルスの上級編です。",
        slug: "/tutorial-extras/",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "tutorial-extras",
        },
      ],
    },
  ],

  // Usage
  usageSidebar: [
    // category: ドロップダウンを作成
    {
      type: "category",
      label: "使い方", // サイドバー用
      collapsible: true, // ▼ を表示するかしないか
      collapsed: false,
      link: {
        type: "generated-index",
        title: "使い方", // 自動生成されるインデクスページ用
        description: "使い方のインデクスページです。",
        slug: "/usage/", // インデクスページURL用
      },
      items: [
        {
          type: "autogenerated",
          dirName: "usage",
        },
      ],
    },
    // html: サイドバーにhtmlを埋め込む
    {
      type: "html",
      value: "<hr />",
    },
    // link: 外部リンク
    { type: "link", label: "ヤフー", href: "http://www.yahoo.co.jp" },
    // link: 内部リンク
    { type: "link", label: "ホーム", href: "/" },
  ],
};

export default sidebars;
