import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  tutorialSidebar: [
    "tutorial",
    {
      type: "category",
      label: "基本的な使い方",
      items: [
        {
          type: "autogenerated",
          dirName: "tutorial-basics",
        },
      ],
    },
    {
      type: "category",
      label: "上級編",
      items: [
        {
          type: "autogenerated",
          dirName: "tutorial-extras",
        },
      ],
    },
  ],

  // my sidebar
  usageSidebar: [
    {
      type: "category",
      label: "使い方",
      //link: { type: "doc", id: "usage/index" },
      items: [
        {
          type: "autogenerated",
          dirName: "usage",
        },
      ],
    },
  ],
};

export default sidebars;
